apiVersion: apps/v1
kind: Deployment
metadata:
  name: screeningmanage
  namespace: skcc-ns
  labels:
    app: screeningmanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screeningmanage
  template:
    metadata:
      labels:
        app: screeningmanage
    spec:
      containers:
        - name: screeningmanage
          image: 496278789073.dkr.ecr.ap-southeast-2.amazonaws.com/user14-screeningmanage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: api.url.payment
              valueFrom:
                configMapKeyRef:
                  name: my-config
                  key: api.url.payment
          
---

apiVersion: v1
kind: Service
metadata:
  name: screeningmanage
  namespace: skcc-ns
  labels:
    app: screeningmanage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: screeningmanage